config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'groups#index'
  resources :users, only: %i[index edit update]
  resources :groups, only: %i[new create edit update] do
    resources :messages, only: %i[index create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true

  has_many :members
  has_many :users, through: :members
  has_many :messages

  def show_last_message
    if (last_message = messages.last).present?
      last_message.body? ? last_message.body : '画像が投稿されています'
    else
      'まだメッセージはありません。'
    end
  end
end

app/models/member.rb
class Member < ApplicationRecord
  validates :user_id, presence: true
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  validates :body, presence: true, unless: :img?

  belongs_to :user
  belongs_to :group

  mount_uploader :img, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :members
  has_many :groups, through: :members
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[edit update]
  def index; end

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: "新しいグループを作成しました"
    else
      render :new
    end
  end

  def edit; end

  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: 'グループを作成しました'
    else
      render :edit
    end
  end

  private

  def group_params
    params.require(:group).permit(:name, user_ids: [])
  end

  def set_group
    @group = Group.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @group = Group.find(params[:group_id])
    @messages = Message.new
    @messages = @group.messages.includes(:user)
    respond_to do |format|
      format.html
      format.json
    end
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.html { redirect_to group_messages_path(@group) }
        format.json
      end
    else
      @message = @group.messages.includes(:user)
      flash.now[:alert] = "メッセージを入力して下さい"
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:body, :img).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.where('name LIKE(?)', "%#{params[:keyword]}%").where.not(id: current_user.id.to_s)
    respond_to do |format|
      format.html
      format.json
    end
  end

  def edit; end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def format_posted_time(time)
    time.to_s(:default)
  end
end

app/views/groups/_form.html.haml
= form_for group do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :name, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'グループ名を入力してください'

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      =f.label :for, "チャットメンバーを追加", class: 'chat-group-form__label'
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input#user-search-field.chat-group-form__input{placeholder: "追加したいユーザー名を入力してください", type: "text"}
        #user-search-result

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :for, "チャットメンバー", class: 'chat-group-form__label'
    .chat-group-form__field--right
      #chat-group-users
        - group.users.each do |user|
          .chat-group-user.clearfix.js-chat-member{id: "chat-group-user-#{user.id}"}
            %input{name: "group[user_ids][]", type: "hidden", value: "#{user.id}"}
            %p.chat-group-user__name #{user.name}
            %a.user-search-remove.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn 削除

  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render 'form', {group: @group}

app/views/groups/index.html.haml
.wrapper

  = render 'groups/../shared/sidebar'

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render 'form', {group: @group}

app/views/layouts/_notification.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application'
  %body
    = render 'layouts/notification'
    = yield

app/views/messages/_message.html.haml
.message{ "data-message-id": "#{message.id}"}
  %ul.user
    %li.list.user__name
      = message.user.name
    %li.list.user__date
      = format_posted_time(message.created_at)
  %p.text
    - if message.body.present?
      = message.body
    = image_tag message.img.url, class: 'lower-message__image' if message.img.present?

app/views/messages/index.html.haml
- @message = Message.new
.wrapper
  = render 'messages/../shared/sidebar'

  .main
    .header.clearfix
      .header-left
        %p.header-left__name
          = @group.name
        %p.header-left__user
          Member :
          - @group.users.each do |user|
            = user.name
      .header-right
        = link_to "edit", edit_group_path(@group), class: "header-right__edit"
    .content
      = render partial: 'message', collection: @messages
    .form
      = form_for [@group, @message] do |f|
        = f.text_field :body, class: 'form__message textbox', placeholder: 'type a message'
        .form__mask
          = f.label :img, class: 'form__mask__image' do
            = fa_icon 'picture-o', class: 'icon'
            = f.file_field :img, class: 'hidden'
        = f.submit 'Send', class: 'form__submit'

app/views/shared/_sidebar.html.haml
.side-bar.clearfix
  .header
    %p.header__name
      = current_user.name
    %ul.header__lists
      %li.list
        = link_to new_group_path do
          = fa_icon 'pencil-square-o', class: 'icon'
      %li.list
        = link_to edit_user_path(current_user) do
          = fa_icon 'cog', class: 'icon'
  .groups
    .group
      - current_user.groups.each do |group|
        = link_to group_messages_path(group) do
          .group__name
            = group.name
          .group__message
            = group.show_last_message

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.creafix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト",destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      =form_for(current_user) do |f|
        .field
          .filed-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .f.field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'